### ISSUE TITLE
Habilitar TravisCI 

### ISSUE THREAD

**Issue by lucaskatayama** [lucaskatayama/unicampi-browser#1]
@gabisurita poderia habilitar o projeto no TravisCI?

**Comment by gabisurita** [comment]
Se eu não me engano, como criador do repositório você consegue fazer isso, não?

Mas está feito, verifique se está ok :)

**Comment by lucaskatayama** [comment]
eu não consegui... porque o Repo esta na organização.. e eu não estava como admin... dai  o Travis negou

---- On Sun, 20 Nov 2016 11:27:59 -0200 notifications@github.com wrote ----

Se eu não me engano, como criador do repositório você consegue fazer isso, não?

Mas está feito :)
